#ifndef PARSER_ADD_HH
#define PARSER_ADD_HH
#include <arg.hh>
class ParserAdd
{
public:
	virtual ~ParserAdd() {}
	// add options to parser
	virtual void addto_parser(arg::Parser & /*parser*/) {}
	// Commit parsed value to the actual parameters.
	//   For buffered parser options, like that generated by prm::Argu,
	//   this should be called after parsing.
	virtual bool alter() {return false;}
};
#endif
